services:
    server:
        build: .
        image: user_backend
        env_file:
            - .env
        volumes:
            - ./src:/src
        working_dir: /src/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db

    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        expose:
            - 5432
        volumes:
            - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    name: postgres_db