# Generated by Django 4.2.10 on 2024-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcgModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Создано"),
                            ("Added", "Добавлено фото"),
                            ("Detection", "ЭКГ на разметке"),
                            ("Detected", "ЭКГ размечена"),
                            ("Digitizing", "ЭКГ на оцифровке"),
                            ("Digitized", "ЭКГ оцифровано"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("path", models.FilePathField(blank=True)),
            ],
        ),
    ]
