version: "3.9"

services:
  yolo-detector:
    build: .
    container_name: yolo-detector
    command: uvicorn main:app --reload --host 0.0.0.0 --port=8010
    ports:
      - "8010:8010"
    volumes:
      - ./src:/src
      - ./media:/media
    env_file:
      - src/.env
    networks:
      - user_backend_ecg_network

networks:
    user_backend_ecg_network:
      external: true